# NOTE: For the plugin to function properly the option "hopper.disable-move-event" must be disabled in papers config, if you use paper.
# General settings
general:
  # Default: English (en-US) - no download required.
  # This defines the default language. You can place multiple locales in the plugin's "Language" folder to display different locales depending on the player's locale.
  # You can access translations maintained by the community in our Discord: https://discord.gg/B4MAJVk
  # To access translations, other than en-US, execute /translations in the Discord server.
  language: 'en-US'
  # Worlds where upgradeable hoppers should be able to be placed.
  worlds_list:
    - 'world'

  # Set the format of all economy related displays.
  # Info: https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html
  # NOTE: This setting requires server reload / restart.
  eco-format:
    normal: '$#,##0.00'
    # The short format will use the normal format if the value is lower than 1000.
    # If the value is higher or equal than 1000, it will return {value} divided by 1000.
    # This format is only used by a small amount of messages.
    short: '${value}k'


# Database settings
database:
  # MySQL
  mysql:
    # Enable this to use MySQL instead of "file based"
    # SQLite. For performance improvement it's recommended to
    # use MySQL. If you don't have access to a MySQL server,
    # just let this disabled (false).
    enabled: false
    ip-address: 'localhost'
    port: '3306'
    database: 'upgradeablehoppers'
    # It is highly recommended to set a unique table prefix if the plugin shares a database with other plugins.
    table-prefix: 'hoppers'
    user: 'minecraft'
    password: 'password'


command:
  # Should players need to confirm their purchase at /Hopper get?
  get-confirm: false
  # Set aliases
  # for /UpgradeableHoppers command
  # NOTE: These settings require server reload / restart.
  alias:
    upgradeablehoppers_list:
      - hopper
      - hoppers
      - h
      - uhopper
      - uhoppers
      - uh


# Hopper Settings
hopper:
  # Allow only the owner
  # of the hopper item
  # to place it down.
  only-owner: true
  # Item settings /Hopper get
  item:
    # Allow buying more hoppers even if the player already reached the maximum amount of PLACED hoppers?
    # Command: /Hoppers get [amount]
    over-max: true

  # Restrict normal hoppers, which are no upgradeable hoppers.
  vanilla:
    # Allow the crafting of normal hoppers?
    crafting: true
    # Allow the placing of normal hoppers?
    placing: true
    # Should normal hoppers (not from this plugin) be converted on placement?
    convert: false

  # Set the default hopper settings
  # All settings can be found here:
  # https://github.com/Angeschossen/UpgradeableHoppersAPI/blob/master/src/main/java/me/angeschossen/upgradeablehoppers/api/enums/HopperFlag.java
  default-settings_list:
    - SUCTION_ENABLED

  # Teleport to hoppers in /Hopper list
  # Permission uhoppers.teleport
  teleportation:
    # Set teleportation cost.
    cost_2: 200

  # Should only players with the uhoppers.upgrade permission be able to upgrade any hopper?
  upgrade-perm: false


# NOTE: These settings require server reload / restart.
optimization:
  redstone:
    # Should hoppers stop transferring items if they're powered by redstone?
    pause-on-signal: false
    # Should the emitted redstone signal strength be updated with every item insertion and removal?
    # This affects both hoppers and links.
    update-signal:
      enabled_2: true
      # If disabled, the redstone signal will only be updated to on or off. Means it will only change if the
      # container state goes from empty -> full or full -> empty.
      # This will help increasing performance, but may make it impossible to display the storage capacity using redstone lamps.
      precise: false

  # Should the transfer amount from levels.yml also be applied to pulling items from containers above the hopper?
  item-pull-amount: true

  # Should an item and link combination be put on cooldown, if the item can't be added to the specific link?
  # The item will then be added to the next available link. This also takes the insert by order feature into account.
  # This helps servers that use a fast transfer speed (like 10 ticks). This prevents checking full chests over and over again.
  # This also applies to hoppers.
  full-cooldown: true

  # Should the inventory state of links be synced regularly?
  # You should keep this enabled, if you use any 3rd party plugins that modify containers.
  inv-sync: true


# General Teleportation Settings
# Command specific teleportation options can be find in their sections.
teleport:
  # General teleportation cost. Some features might have specific options, which override this.
  costs: 0
  # Set the cost of any teleportation to 0 for players that joined the server for the first time.
  # You can define a time span here. Example: 1d = players that joined the server 23 hours ago, won't pay for any teleportation.
  first-join_time: 0h
  # Wait-time
  # Timeunit: seconds
  wait: 3



# Link / destination settings
link:
  # Should destinations be visualized when clicking on the setup link item in the hopper menu?
  visualization: true
  # Should whitelist mode be activated by default?
  whitelist: false
  # Should strict filtering be enabled by default?
  strict: false

  type:
    furnace:
      # Define a list of additional blocks that can be smelt in a furnace.
      # For example blocks from data-packs.
      smelt_list: []

# Sound configuration
# Format: SOUND:VOLUME:PITCH
# The volume and pitch parameter are optional. They allow you to control how the sound is played.
# Disabling a sound: Just set it to ''
sounds:
  # Sound which should be played whenever a player gets teleported by Lands.
  # Sounds can be disabled by setting their value to ''
  teleport:
    teleported_sound: 'ENTITY_ENDERMAN_TELEPORT'
    countdown_sound: 'BLOCK_LEVER_CLICK'

# Protection settings
protection:
  # Should upgradeable hoppers be protected?
  # NOTE: If disabled, everyone can destroy, upgrade, open the hopper.
  enabled_3: true
  # Should TnT explosions be able to destroy the hoppers? Their items will drop.
  anti-explosive: true
  # Supports: Lands (https://www.spigotmc.org/resources/53313), SuperiorSkyblock2, BentoBox, PlotSquared, WorldGuard
  # Allow players, which are trusted in the region where the hopper is located in, to edit the hopper?
  allow-region-members: false


# 3rd party plugin integrations
integration:
  # Lands (https://www.spigotmc.org/resources/53313)
  lands:
    # Should players be allowed to place hoppers only in claimed areas?
    # This disallows placing upgradeable hoppers in wilderness.
    only-land: false

  # Preventing linking containers in region where the player isn't trusted?
  # NOTE: This setting requires server reload / restart.
  prevent-untrusted-link: true

  # If you use any 3rd party plugin for item stacking, please enable it here to make sure UpradeableHoppers can read the correct item stack amount.
  # Currently supported: WildStacker, RoseStacker, zItemStacker
  # Yours isn't listed? 3rd party developers can integrate their ItemStacker via this method: https://github.com/Angeschossen/UpgradeableHoppersAPI/blob/25dc754a635908de161685d0fa0f9795d2f65bab/src/main/java/me/angeschossen/upgradeablehoppers/api/UpgradeableHoppersAPI.java#L28
  item-stacker: 'default'
  # Economy settings
  # If all types are disabled, the item based economy will be used instead.
  # NOTE: When changing these option you might also want to adjust the "eco-format" in this config.
  economy:
    vault:
      # You need an economy plugin, which supports Vault, to let this work.
      enabled_10: true
      # Server bank account name. Spendings go here.
      server-bank: ''
    # Player experience
    exp:
      enabled_15: false
    # Item currency is used when all other economy options are disabled or unavailable.
    # The currency item can be edited in the GUI language file at the "currency" item.
    items:
      # If enabled, only items that have the same name, lore etc. will belong to the currency.
      # Not just items of the same type or items with the same model-data.
      strict_2: false

# Configure logging
logging:
  # We might ask you to enable this, when you submit a bugreport.
  debug: false