name: UpgradeableHoppers
main: me.angeschossen.upgradeablehoppers.UpgradeableHoppers
version: ${project.version}
author: Angeschossen
api-version: 1.13
softdepend: [ShopGUIPlus, Lands, Vault, SuperiorSkyblock2, BentoBox, WildStacker, WildChests, RoseStacker, AdvancedChests, PlotSquared, WorldGuard]


commands:
  upgradeablehoppers:
    description: UpgradeableHoppers main command.

permissions:
  uhoppers.*:
    description: Access to all UpgradeableHoppers actions
    children:
      uhoppers.admin.*:
        description: Access to all admin actions.
        children:
          uhoppers.admin.command.*:
            description: Access to all admin commands.
            children:
              uhoppers.admin.command.give:
                description: Access to /uhoppers admin give
              uhoppers.admin.command.about:
                description: Access to /uhoppers admin about
              uhoppers.admin.command.import:
                description: Access to /uhoppers admin import
              uhoppers.admin.command.listperms:
                description: Access to /uhoppers admin listperms
              uhoppers.admin.command.migratedb:
                description: Access to /uhoppers admin migratedb
              uhoppers.admin.command.reload:
                description: Access to /uhoppers admin reload

      uhoppers.hoppers.<number>:
        description: Give players permission to create specific amount of hoppers.
      uhoppers.links.<number>:
        description: Give players permission to link specific amount of containers per hopper.
      uhoppers.teleportation:
        description: Allow teleportation to a hopper through /Hopper list
      uhoppers.command.*:
        description: Access to all commands.
        children:
          uhoppers.command.get:
            description: Access to /upgradeablehoppers get
          uhoppers.command.help:
            description: Access to /upgradeablehoppers help
          uhoppers.command.view:
            description: Access to /upgradeablehoppers view
          uhoppers.command.list:
            description: Access to /upgradeablehoppers list
          uhoppers.command.abort:
            description: Access to /upgradeablehoppers abort

      uhoppers.bypass.*:
        description: Bypass protections etc.
        children:
          uhoppers.bypass.open:
            description: Open other players hoppers.
          uhoppers.bypass.upgrade:
            description: Upgrade other players hoppers.
          uhoppers.bypass.delete:
            description: Delete other players hoppers.
          uhoppers.bypass.claim:
            description: Allow linking in claims the player is not trusted in.
          uhoppers.bypass.only-land:
            description: Bypass only-land option in config.yml and not being able to place hoppers in lands they're not trusted in.
          uhoppers.bypass.vanilla.*:
            description: Bypass all vanilla hopper settings.
            children:
              uhoppers.bypass.vanilla.craft:
                description: Bypass vanilla hopper craft setting.
              uhoppers.bypass.vanilla.place:
                description: Bypass vanilla hopper place setting.

      uhoppers.upgrade:
        description: Only allow players with this permission to upgrade any hopper, if config option upgrade-perm enabled.

      uhoppers.teleport.*:
        description: Allow all teleportation.
        children:
          uhoppers.teleport.hopper:
            description: Allow teleportation to hoppers.
            default: true